### ISSUE TITLE
Error when not passing any functions to a .series()

### ISSUE THREAD

**Issue by whyhankee** [whyhankee/flw#5]
11:44:40 0|api      | TypeError: Cannot read property 'name' of undefined
11:44:40 0|api      |     at callFunction (/Users/wijhenke/git/xxxx/xxxx-api/node_modules/flw/flw.js:46:43)
11:44:40 0|api      |     at Object.series (/Users/wijhenke/git/xxxx/xxxx-api/node_modules/flw/flw.js:39:12)

Check other methods as well

**Comment by whyhankee** [comment]
Fixed in v0.0.16
